version: '3.8'
services:
  user-service:
    build: ./user-service
    ports:
      - "4001:4001"
  
  product-service:
    build: ./product-service
    ports:
      - "4002:4002"

  bff:
    build: ./bff
    ports:
      - "4000:4000"
    depends_on:
      - user-service
      - product-service
