version: "3.8"

services:
<<<<<<< HEAD
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db # <--- Sửa lỗi ở đây
    networks:
      - micro_net

=======
>>>>>>> 7a78ef7ee8898a54ffeb7383b6213dff36b66ad6
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - micro_net
<<<<<<< HEAD
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 5
=======
>>>>>>> 7a78ef7ee8898a54ffeb7383b6213dff36b66ad6

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - micro_net
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:7.0
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - micro_net

  bff:
    build:
      context: .
      dockerfile: bff/Dockerfile
    container_name: bff
    ports:
      - "5000:5000"
    env_file:
      - ./bff/.env
    depends_on:
      user-service:
        condition: service_started
      product-service:
        condition: service_started
      transaction-service:
        condition: service_started
    networks:
      - micro_net

  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile
    container_name: product-service
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - DB_URL=mongodb://mongo:27017/productDB
      - KAFKA_BROKER=kafka:9092
    depends_on:
<<<<<<< HEAD
      mongo:
        condition: service_started
      kafka:
        condition: service_healthy
=======
      - mongo
      - kafka
>>>>>>> 7a78ef7ee8898a54ffeb7383b6213dff36b66ad6
    networks:
      - micro_net

  transaction-service:
    build:
      context: .
      dockerfile: transaction-service/Dockerfile
    container_name: transaction-service
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
      - DB_URL=mongodb://mongo:27017/transactionDB
      - JWT_SECRET=user_secret_key
      - KAFKA_BROKER=kafka:9092
    depends_on:
<<<<<<< HEAD
      mongo:
        condition: service_started
      kafka:
        condition: service_healthy
=======
      - mongo
      - kafka
>>>>>>> 7a78ef7ee8898a54ffeb7383b6213dff36b66ad6
    networks:
      - micro_net

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: user-service
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - JWT_SECRET=user_secret_key
      - KAFKA_BROKER=kafka:9092
      - DB_URL=mongodb://mongo:27017/userDB
    depends_on:
<<<<<<< HEAD
      mongo:
        condition: service_started
      kafka:
        condition: service_healthy
    networks:
      - micro_net

volumes:
  mongo_data:

networks:
  micro_net:
    driver: bridge
=======
      - mongo
      - kafka
    networks:
      - micro_net

networks:
  micro_net:
    driver: bridge
>>>>>>> 7a78ef7ee8898a54ffeb7383b6213dff36b66ad6
