version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log
    networks:
      - micro_net
    healthcheck:
      test: ["CMD-SHELL", "echo stat | nc localhost 2181"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test:
        [
          "CMD",
          "bash",
          "-c",
          "kafka-topics --bootstrap-server localhost:9092 --list",
        ]
      interval: 10s
      timeout: 5s
      retries: 15 
    networks:
      - micro_net

  mongo:
    image: mongo:7.0
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - micro_net
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s 
    volumes:
      - mongo-data:/data/db

  bff:
    build:
      context: .
      dockerfile: bff/Dockerfile
    container_name: bff
    ports:
      - "5000:5000"
    env_file:
      - ./bff/.env
    depends_on:
      user-service:
        condition: service_started
      product-service:
        condition: service_started
      transaction-service:
        condition: service_started
    networks:
      - micro_net

  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile
    container_name: product-service
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - DB_URL=mongodb://mongo:27017/productDB
      - KAFKA_BROKER=kafka:9092
      - KAFKA_GROUP_ID=product-service-group
    depends_on:
      mongo:
        condition: service_healthy
      kafka:
        condition: service_healthy
      zookeeper:
        condition: service_healthy
    networks:
      - micro_net

  transaction-service:
    build:
      context: .
      dockerfile: transaction-service/Dockerfile
    container_name: transaction-service
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
      - DB_URL=mongodb://mongo:27017/transactionDB
      - USER_SERVICE_URL=http://user-service:5001
      - PRODUCT_SERVICE_URL=http://product-service:5002
      - JWT_SECRET=user_secret_key
      - KAFKA_BROKER=kafka:9092
      - KAFKA_GROUP_ID=transaction-service-group
    depends_on:
      mongo:
        condition: service_healthy
      kafka:
        condition: service_healthy
      zookeeper:
        condition: service_healthy
    networks:
      - micro_net

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: user-service
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - JWT_SECRET=user_secret_key
      - KAFKA_BROKER=kafka:9092
      - KAFKA_GROUP_ID=user-service-group
      - DB_URL=mongodb://mongo:27017/userDB
    depends_on:
      mongo:
        condition: service_healthy
      kafka:
        condition: service_healthy
      zookeeper:
        condition: service_healthy
    networks:
      - micro_net

networks:
  micro_net:
    driver: bridge

volumes:
  mongo-data:
  zookeeper-data:
  zookeeper-log:
  kafka-data: