services:
  user-service:
    build: ./user-service
    # ❌ KHÔNG cần khai báo ports
    # Dockerfile phải có: EXPOSE 4001

  product-service:
    build: ./product-service
    # ❌ KHÔNG cần khai báo ports
    # Dockerfile phải có: EXPOSE 4002

  bff:
    build: ./bff
    ports:
      - "4000:4000" # chỉ mở port cho BFF
    depends_on:
      - user-service
      - product-service
