version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: product-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - micro_net

  bff:
    build:
      context: .
      dockerfile: bff/Dockerfile
    container_name: bff
    ports:
      - "5000:5000"
    env_file:
      - ./bff/.env
    depends_on:
      - user-service
      - product-service
      - transaction-service
    networks:
      - micro_net

  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile
    container_name: product-service
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - DB_URL=mongodb://mongo:27017/productDB
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - mongo
    networks:
      - micro_net

  transaction-service:
    build:
      context: .
      dockerfile: transaction-service/Dockerfile
    container_name: transaction-service
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
      - DB_URL=mongodb://mongo:27017/transactionDB
      - JWT_SECRET=user_secret_key
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - mongo
    networks:
      - micro_net

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: user-service
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - JWT_SECRET=user_secret_key
      - KAFKA_BROKER=kafka:9092
      - DB_URL=mongodb://mongo:27017/userDB
    depends_on:
      - kafka
    volumes:
      - ./user-service:/app
      - ./kafka-wrapper:/app/kafka-wrapper
