services:
  user-service:
    build: ./user-service

  product-service:
    build: ./product-service

  transaction-service:
    build: ./transaction-service

  bff:
    build: ./bff
    ports:
      - "5000:5000"
    depends_on:
      - user-service
      - product-service
      - transaction-service
