services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: 'broker' # <--- ADD THIS LINE

  user-service:
    build:
      context: .
      dockerfile: ./user-service/Dockerfile
    container_name: user-service
    ports:
      - "5001:5001"
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: kafka:29092
    volumes:
      - ./user-service:/app
      - ./kafka-wrapper:/app/kafka-wrapper

  product-service:
    build:
      context: .
      dockerfile: ./product-service/Dockerfile
    container_name: product-service
    ports:
      - "5002:5002"
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: kafka:29092
    volumes:
      - ./product-service:/app
      - ./kafka-wrapper:/app/kafka-wrapper

  transaction-service:
    build:
      context: .
      dockerfile: ./transaction-service/Dockerfile
    container_name: transaction-service
    ports:
      - "5003:5003"
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: kafka:29092
    volumes:
      - ./transaction-service:/app
      - ./kafka-wrapper:/app/kafka-wrapper

  bff:
    build:
      context: .
      dockerfile: ./bff/Dockerfile
    container_name: bff
    ports:
      - "5000:5000"
    depends_on:
      - user-service
      - product-service
      - transaction-service
      - kafka
    environment:
      KAFKA_BROKERS: kafka:29092
    volumes:
      - ./bff:/app
      - ./kafka-wrapper:/app/kafka-wrapper
