# transaction-service/Dockerfile
FROM node:20

# Thiết lập thư mục làm việc
WORKDIR /app

# Copy shared Kafka Wrapper first, since it changes less often
# The '..' is a relative path to the parent directory on the host machine
COPY ../kafka-wrapper ./kafka-wrapper

# Copy package.json and package-lock.json to leverage Docker's build cache
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application's code into the container
COPY . .

# Khai báo port service lắng nghe
EXPOSE 5003

# Lệnh khởi động service
CMD ["node", "index.js"]
