FROM node:20

WORKDIR /app

# Copy package.json + kafka-wrapper
COPY package*.json ./
COPY ../kafka-wrapper ./kafka-wrapper
COPY ../kafka-wrapper/package*.json ./kafka-wrapper/

# Cài dependencies (bao gồm kafka-wrapper)
RUN npm install

# Copy toàn bộ code service
COPY . .

EXPOSE 5003
CMD ["npm", "start"]
