# Cấu hình Dockerfile cho transaction-service
FROM node:20

WORKDIR /app

# Sao chép các file package và thư mục kafka-wrapper
COPY transaction-service/package*.json ./
COPY package*.json ./
COPY kafka-wrapper ./kafka-wrapper

# Cài đặt dependencies (bao gồm cả child-process sau khi đã chỉnh sửa package.json)
RUN npm install

# Sao chép toàn bộ mã nguồn service
COPY transaction-service/. .

EXPOSE 5003
CMD ["npm", "start"]